/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004f4f",
        "secondary-fixed": "#d0e8d9",
        "surface-variant": "#e0e3e2",
        "surface-bright": "#f7faf9",
        "surface-container-high": "#e6e9e8",
        "on-secondary-fixed-variant": "#364b40",
        "secondary-container": "#cde6d6",
        "secondary": "#4d6357",
        "on-primary-fixed": "#002020",
        "tertiary": "#264c5c",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#001f2a",
        "primary-fixed-dim": "#84d4d3",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b4ccbd",
        "on-error": "#ffffff",
        "on-surface": "#181c1c",
        "outline": "#6e7979",
        "on-surface-variant": "#3e4948",
        "tertiary-fixed": "#c2e8fc",
        "error": "#ba1a1a",
        "surface-container-low": "#f1f4f3",
        "surface": "#f7faf9",
        "on-primary-container": "#97e7e6",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006a6a",
        "on-secondary-fixed": "#0a1f16",
        "primary": "#005050",
        "tertiary-container": "#3f6475",
        "on-error-container": "#93000a",
        "primary-fixed": "#a0f0f0",
        "inverse-surface": "#2d3131",
        "background": "#f7faf9",
        "surface-container-highest": "#e0e3e2",
        "tertiary-fixed-dim": "#a6cce0",
        "surface-container": "#ebeeee",
        "on-tertiary-fixed-variant": "#254b5c",
        "on-background": "#181c1c",
        "outline-variant": "#bec9c8",
        "inverse-on-surface": "#eef1f0",
        "on-secondary-container": "#51685b",
        "inverse-primary": "#84d4d3",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#b9dff3",
        "primary-container": "#006a6a",
        "surface-dim": "#d7dbda"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    }
  },
  plugins: [],
}
